url: http://www.quant.fm
baseurl:

# Site settings
title: Quant FM
email: hi@quant.fm
description: "这里是quant fm,致力于普及量化投资知识的podcast"

# Team names, titles and social links
people:
- name: Alfred
  pic: 1
  position: Founder & 主播
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Veratulips
  pic: 2
  position: Founder & 主播
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: You
  pic: 3
  position: 主播
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url:
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: http://github.com/quantfm

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty